name: Build BE6500 OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 清理磁盘
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: 拉取源码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential flex bison git libncurses-dev gawk unzip libssl-dev python3-distutils rsync ccache

      - name: feeds更新
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 写入配置并defconfig
        run: |
          cat > .config <<'EOF'
CONFIG_TARGET_ipq53xx=y
CONFIG_TARGET_ipq53xx_generic=y
CONFIG_TARGET_ipq53xx_generic_DEVICE_jdcloud_be6500=y
CONFIG_DEVEL=y
CONFIG_CCACHE=y
EOF
          make defconfig

      - name: make download
        run: make -j1 download

      - name: 编译固件
        run: |
          make -j$(nproc) V=s || make -j1 V=s

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: BE6500‑firmware
          path: bin/targets/ipq53xx/generic/*.bin

